[package]
name = "aoc22"
version = "0.1.0"
edition = "2021"
authors = ["Burhan Keten"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
